- name: Install Java in Ubuntu AppServer
  hosts: java_servers
  tasks:
  - name: installing Java in Ubuntu AppServer
    ansible.builtin.apt:
      name: openjdk-11-jdk
      state: present
      update_cache: yes
